/**
 * Halo Motion springs for JS-driven transitions — the same curves as the CSS tokens
 * --spring-snappy / --spring-smooth / --spring-gentle in halo.css (generated by
 * scripts/halo-spring.py): a damped spring normalised to settle
 * (envelope < 0.2%) exactly at t = 1, so the transition's duration is its settle time.
 */

const EPS = 0.002;

const makeSpring = (zeta: number) => {
	const w0 = Math.log(1 / EPS) / zeta;
	const wd = w0 * Math.sqrt(1 - zeta * zeta);
	const a = zeta * w0;
	return (t: number) => {
		if (t <= 0) return 0;
		if (t >= 1) return 1;
		return 1 - Math.exp(-a * t) * (Math.cos(wd * t) + (a / wd) * Math.sin(wd * t));
	};
};

/** Micro interactions: no visible overshoot. */
export const springSnappy = makeSpring(0.92);
/** Menus, panels, pages: ~1% overshoot. */
export const springSmooth = makeSpring(0.82);
/** The few camera moves: ~3% overshoot, a soft settle. */
export const springGentle = makeSpring(0.74);

/** Leaving is quick and plain: things go away faster than they arrive. */
export const exitEase = (t: number) => t * t * (3 - 2 * t);

export const DUR = { micro: 160, std: 240, hero: 560, exit: 140 } as const;

export const prefersReducedMotion = (): boolean =>
	typeof window !== 'undefined' &&
	typeof window.matchMedia === 'function' &&
	window.matchMedia('(prefers-reduced-motion: reduce)').matches;
